const projectItems = [
  {
    slug: "verilog-playground",
    image: "assets/verilog-playground.gif",
    title: "Verilog Playground",
    startDate: "May, 2018",
    description:
      "FPGA board simulator that modernized COA classes by removing physical board-access bottlenecks and accelerating build/test cycles.",
    detailsFile: "projects/verilog-playground.md",
    imageFit: "contain",
  },
  {
    slug: "portfolio-api",
    image: "assets/project-1.svg",
    title: "Portfolio API",
    startDate: "March, 2024",
    description: "A REST API for project and article management with JWT auth and OpenAPI docs.",
    detailsFile: "projects/portfolio-api.md",
  },
  {
    slug: "design-system-kit",
    image: "assets/project-2.svg",
    title: "Design System Kit",
    startDate: "August, 2023",
    description: "Reusable UI components and tokens for consistent, accessible web interfaces.",
    detailsFile: "projects/design-system-kit.md",
  },
  {
    slug: "cli-productivity-tools",
    image: "assets/project-3.svg",
    title: "CLI Productivity Tools",
    startDate: "May, 2022",
    description: "A set of CLI utilities for automating repetitive engineering workflows.",
    detailsFile: "projects/cli-productivity-tools.md",
  },
  {
    slug: "video-automation",
    image: "assets/project-4.svg",
    title: "Video Automation",
    startDate: "November, 2023",
    description: "Batch utilities for preparing and publishing YouTube content efficiently.",
    detailsFile: "projects/video-automation.md",
  },
  {
    slug: "interview-prep-dashboard",
    image: "assets/project-5.svg",
    title: "Interview Prep Dashboard",
    startDate: "February, 2025",
    description: "Progress tracker and daily problem planner for coding interviews.",
    detailsFile: "projects/interview-prep-dashboard.md",
  },
  {
    slug: "photo-journal",
    image: "assets/project-6.svg",
    title: "Photo Journal",
    startDate: "June, 2024",
    description: "A lightweight media gallery optimized for responsive viewing and quick updates.",
    detailsFile: "projects/photo-journal.md",
  },
];
